[build]
  command = "yarn build"
  functions = "lambda" #  netlify-lambda reads this
  publish = "build"


[[headers]]
  for = "/*"
  [headers.values]
    'Access-Control-Allow-Origin' = "*"
    'Access-Control-Allow-Headers' = "*"