/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface UrlPreviewCard {
    'proxyUrl': string;
    'type': type;
    'url': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLUrlPreviewCardElement extends Components.UrlPreviewCard, HTMLStencilElement {}
  var HTMLUrlPreviewCardElement: {
    prototype: HTMLUrlPreviewCardElement;
    new (): HTMLUrlPreviewCardElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'url-preview-card': HTMLUrlPreviewCardElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface UrlPreviewCard {
    'proxyUrl'?: string;
    'type'?: type;
    'url'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'url-preview-card': UrlPreviewCard;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'url-preview-card': LocalJSX.UrlPreviewCard & JSXBase.HTMLAttributes<HTMLUrlPreviewCardElement>;
    }
  }
}


