/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CodeHighlighter {}
  interface ComponentDocs {}
  interface UrlPreviewCard {
    'card': {
      title: string,
      description: string,
      img: string,
    };
    'customProxy': boolean;
    'fetchError': () => Promise<void>;
    'target': string;
    'updateCard': (card: any) => Promise<void>;
    'url': string;
    'variant': 'small' | 'large';
  }
}

declare global {


  interface HTMLCodeHighlighterElement extends Components.CodeHighlighter, HTMLStencilElement {}
  var HTMLCodeHighlighterElement: {
    prototype: HTMLCodeHighlighterElement;
    new (): HTMLCodeHighlighterElement;
  };

  interface HTMLComponentDocsElement extends Components.ComponentDocs, HTMLStencilElement {}
  var HTMLComponentDocsElement: {
    prototype: HTMLComponentDocsElement;
    new (): HTMLComponentDocsElement;
  };

  interface HTMLUrlPreviewCardElement extends Components.UrlPreviewCard, HTMLStencilElement {}
  var HTMLUrlPreviewCardElement: {
    prototype: HTMLUrlPreviewCardElement;
    new (): HTMLUrlPreviewCardElement;
  };
  interface HTMLElementTagNameMap {
    'code-highlighter': HTMLCodeHighlighterElement;
    'component-docs': HTMLComponentDocsElement;
    'url-preview-card': HTMLUrlPreviewCardElement;
  }
}

declare namespace LocalJSX {
  interface CodeHighlighter {}
  interface ComponentDocs {}
  interface UrlPreviewCard {
    'card'?: {
      title: string,
      description: string,
      img: string,
    };
    'customProxy'?: boolean;
    'onFetchMeta'?: (event: CustomEvent<any>) => void;
    'target'?: string;
    'url'?: string;
    'variant'?: 'small' | 'large';
  }

  interface IntrinsicElements {
    'code-highlighter': CodeHighlighter;
    'component-docs': ComponentDocs;
    'url-preview-card': UrlPreviewCard;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'code-highlighter': LocalJSX.CodeHighlighter & JSXBase.HTMLAttributes<HTMLCodeHighlighterElement>;
      'component-docs': LocalJSX.ComponentDocs & JSXBase.HTMLAttributes<HTMLComponentDocsElement>;
      'url-preview-card': LocalJSX.UrlPreviewCard & JSXBase.HTMLAttributes<HTMLUrlPreviewCardElement>;
    }
  }
}


